---
stages:
  - deploy

include:
  - remote: https://gitlab.com/megabyte-space/gitlab-ci-templates/-/raw/master/fix/prettier-fix.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-space/gitlab-ci-templates/-/raw/master/propagate/propagate-groups.gitlab-ci.yml
